1、一维数组、二维数组

In [ ]:
# 调用函print()数
print(1)  

1


In [ ]:
import numpy as np

# 将 Python 中的列表、元组或其他可迭代对象 转换为 NumPy 数组
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [ ]:
# 定义一个列表
A = [1,2]
print(A)

[1, 2]


In [5]:
# 将列表[1,2]转化成一维数组
A = np.array([1,2])
print(A)

[1 2]


2、np.shape()函数

In [4]:
# .shape() 用于查看数组的“形状”，也就是数组的 维度结构（几行几列）。
import numpy as np

print(np.shape([[1, 2, 3], [4, 5, 6]]))

A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)

(2, 3)
(2, 3)


In [3]:
# 输出数组的行数
print(A.shape[0])  
# 输出数组的列数
print(A.shape[1])

2
3


3、max()函数

In [36]:
# max()函数返回最大值，可以作用于列表、元组、字符串、多个数等对象。
# 基本语法：max(arg1, arg2)
a = 10
b = 25
print(max(a, b))  

25


In [41]:
list = [1, 3, 5]
print(max(list)) 

5


4、列表与元素的提取

In [ ]:
# 在python中，对于一个列表list，可以通过list[x]来提取第X+1个值
A = [1,2,3,4]
print(A[0])

1
[1, 2]


In [ ]:
print(A[0:2])

5、if语句

In [ ]:
# 在python中，if 语句是 最基本的条件判断语句，它的作用是：当条件满足时，就执行某段代码。
# 基本语法：
# if 条件:
#     语句块1
# else:
#     代码块2
# 只有当条件为真时，才会执行语句块1中的内容，否则就执行语句块2中的内容。
score = 80

if score >= 60:
    print("及格")
else:
    print("不及格")

不及格


6、np.sum()函数

In [10]:
# 在python中，sum()函数用于对数组中的元素进行求和。
# 它可以对数组沿指定轴（axis）进行求和操作，或者直接对整个数组的所有元素进行求和。
# 基本语法：np.sum(a, axis=None, dtype=None, out=None, keepdims=False)
# 参数说明：
# a：待求和的输入数组
# axis：指定沿哪个轴进行求和。默认为 None（所有元素求和）。axis=0为按列求和，axis=1为按行求和。
# dtype：用于计算结果的类型。默认是 None
# out：用于存储结果的数组。如果指定了该参数，结果会存储在这个数组中。
# keepdims：如果设置为 True，则结果会保持原数组的维度
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sum(arr))
print(np.sum(arr, 1))
print(np.sum(arr, 0))

21
[ 6 15]
[5 7 9]


7、np.power()函数

In [19]:
# 在python中，np.power()用于计算数组元素的幂运算。
# 基本语法：np.power(a, b)
# a：底数，可以是一个标量或数组。
# b：指数，可以是一个标量或数组。（若 b 是一个数组，则要求与 a 的形状一致。）
import numpy as np
arr = np.array([1, 2, 3, 4])
result = np.power(arr, 2)
print(result)

[ 1  4  9 16]


In [20]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 3, -1, 1/2])
result = np.power(arr1, arr2)
print(result)

[1.         8.         0.33333333 2.        ]


8、np.argmax()函数

In [31]:
# 在python中，np.argmax()用于返回数组中最大值的索引位置。
# 基本语法：np.argmax(a, axis=None, out=None)
# a：输入的数组。必须是一个 NumPy 数组或可以转换为 NumPy 数组的对象。
# axis：指定查找最大值的索引。默认None（整个数组中查找最大值），axis=0，按列求最大值。axis=1，按行求最大值。
# out：可选，指定用于存储结果的数组。
arr = np.array([10, 20, 30, 40, 50])
index = np.argmax(arr)
print(index) 

4


In [30]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
index = np.argmax(arr, axis=1)
print(index)

[2 2]


9、特征值和特征向量

In [33]:
# 在python中，numpy.linalg.eig()用计算矩阵的特征值和特征向量
# 1、特征值：一个包含所有特征值的数组。
# 2、特征向量：一个包含所有特征向量的矩阵。每一列是一个特征向量，且它们分别对应与特征值中的元素一一对应。

import numpy as np

# 定义新的矩阵 A
A = np.array([[6, 2],
              [1, 3]])

# 使用 numpy.linalg.eig() 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(A)

# 打印特征值
print("特征值:", eigenvalues)

# 打印特征向量
print("特征向量:")
print(eigenvectors)


特征值: [6.56155281 2.43844719]
特征向量:
[[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]
